repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff
      - id: ruff-format
        exclude: ^evals/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args:
          ["--ignore-missing-imports", "--disable-error-code", "misc", "--follow-imports", "silent"]

exclude: ^evals/
