[project]
name = "symphony-v2"
version = "0.1.0"
description = "Dynamic sub-agent creation and orchestration"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mdformat>=0.7.22",
    "openai>=1.72.0",
    "pre-commit>=4.2.0",
    "python-dotenv>=1.1.0",
    "tiktoken>=0.9.0",
]
